volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: ./requirements/wordpress/src/
      o: bind

  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device: ./requirements/mariadb/data
      o: bind

networks:
  internal_network:
    driver: bridge

secrets:
  mariadb_root_password:
    file: ../secrets/mariadb_root_password.txt
  mariadb_user_pwd:
    file: ../secrets/mariadb_user_pwd.txt
  wp_admin_password:
    file: ../secrets/wp_admin_password.txt
  wp_user_password:
    file: ../secrets/wp_user_password.txt

services:
  nginx:
    build: ./requirements/nginx
    image: nginx:latest
    container_name: nginx_container
    depends_on:
      wordpress:
        condition: service_healthy
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html:rw
    networks:
      - internal_network

  wordpress:
    build: ./requirements/wordpress
    image: wordpress:latest
    container_name: wordpress_container
    depends_on:
      mariadb:
        condition: service_healthy
    env_file:
      - .env
    secrets:
      - mariadb_user_pwd
      - wp_admin_password
      - wp_user_password
    volumes:
      - wordpress_data:/var/www/html:rw
    networks:
      - internal_network
    healthcheck:
      test: pgrep -f "php-fpm"
      interval: 5s
      timeout: 3s
      retries: 10

  mariadb:
    build: ./requirements/mariadb
    image: mariadb:latest
    container_name: mariadb_container
    env_file:
      - .env
    secrets:
      - mariadb_root_password
      - mariadb_user_pwd
    volumes:
      - mariadb_data:/var/lib/mysql:rw
    networks:
      - internal_network
    healthcheck:
      test: mariadb -u root -e "SELECT 1"
      interval: 5s
      timeout: 3s
      retries: 10
